version: '3.5'

services:
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && npm run start:prod"
    ports:
      - '3006:3000'
    env_file:
      - .env
    networks:
      - ticketing-network
    restart: always
networks:
  ticketing-network:
